version: 1
groups:
  - annotation: ckanext-fototeca SQL Harvester settings
    options:
      - key: ckanext.fototeca.ign_base_url
        default: https://www.ign.es/web/ign/portal
        validators:
        description: |
          URL of IGN portal.
        required: false